<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>AsyncRAT</AssemblyName>
    <RootNamespace>Server</RootNamespace>
    <Deterministic>true</Deterministic>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>async_icon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <NoWarn>$(NoWarn);WFO1000</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="StreamLibrary\Enums.cs" />
    <Compile Remove="StreamLibrary\IUnsafeCodec.cs" />
    <Compile Remove="StreamLibrary\IVideoCodec.cs" />
    <Compile Remove="StreamLibrary\UnsafeCodecs\UnsafeStreamCodec.cs" />
    <Compile Remove="StreamLibrary\src\JpgCompression.cs" />
    <Compile Remove="StreamLibrary\src\LzwCompression.cs" />
    <Compile Remove="StreamLibrary\src\NativeMethods.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.4.0" />
    <PackageReference Include="dnlib" Version="4.2.0" />
    <PackageReference Include="FCTB" Version="2.16.24" />
    <PackageReference Include="Vestris.ResourceLib" Version="2.2.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.13.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic" Version="4.13.0" />
    <PackageReference Include="Costura.Fody" Version="5.7.0" />
    <PackageReference Include="Fody" Version="6.8.2" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="cGeoIp">
      <HintPath>Resources\cGeoIp.dll</HintPath>
    </Reference>
    <Reference Include="IconExtractor">
      <HintPath>Resources\IconExtractor.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
